### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by svby** [Azer0s/tinygraph#1]
Nice library! I have some suggestions:

- **Undefined behavior!** 🐛
  - [`type_store.cpp`](https://github.com/Azer0s/tinygraph/blob/master/type/type_store.cpp#L17): `type` is copied into the temporary `t`. `t` is then copied again when the constructor for `Type` is invoked, meaning that after `tinygraph_typestore_add` returns, `t` is destroyed and the `char *` key inserted into `types` becomes a dangling pointer. Consider inserting `type_obj->name.c_str()` instead, or...
- **consider using [`string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view)** instead of raw character pointers or `string &`s (and specifying [`less<>`](https://en.cppreference.com/w/cpp/utility/functional/less_void) as your `map`s' comparators). This will allow you to accept both `string &`s and `char *`s due to `string_view`'s implicit constructors.
- **Avoid using `map`'s `operator[]` when retrieving values** ([`graph.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/graph.cpp#L26))
  - When no value is present, because `operator[]` has to return a `T &`, [one is default constructed and returned](https://stackoverflow.com/a/8801171/7366707). This means that the result of `this->vertices[from]` is either a valid `shared_ptr`, or an empty one, which will conveniently segfault(!) when it is used. Consider using `find` with a conditional instead.
- **Avoid using `new`**, instead...
- **consider using [`make_shared`](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared)** (C++ core guidelines: [C.151](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c151-use-make_shared-to-construct-objects-owned-by-shared_ptrs)), which, unlike `shared_ptr(T())`, will properly handle exceptions thrown during object construction
- Avoid redundant moves
  - [`type_store.cpp`](https://github.com/Azer0s/tinygraph/blob/master/type/type_store.cpp#L17): `type` is passed by value. `t` is then copied again when the constructor for `Type` is invoked, meaning the move was essentially a no-op
  - [`type.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/type.cpp#L10)
  - [`vertex.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/vertex.cpp#L8)
  - [`vertex.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/vertex.cpp#L16)
- Consider using [member initializer lists](https://en.cppreference.com/w/cpp/language/initializer_list). This helps with the previous problem, so
   ```cpp
   Vertex::Vertex(std::string name, std::shared_ptr<Type> type) {
       this->name = std::move(name);
       this->type = std::move(type);
   }
   ```
   becomes
   ```cpp
   Vertex::Vertex(std::string name, std::shared_ptr<Type> type) : name(name), type(type) { }
   ```
- Avoid unnecessary copies ([`util.cpp`](https://github.com/Azer0s/tinygraph/blob/master/functions/util.cpp#L8))
- Consider using `static constexpr` constants instead of macros ([`test.cpp`](https://github.com/Azer0s/tinygraph/blob/master/test.cpp#L9)); avoid macros wherever possible
- Avoid accepting `shared_ptr`s by reference when the function takes ownership ([`graph.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/graph.cpp#L17), [`connections.cpp`](https://github.com/Azer0s/tinygraph/blob/master/functions/connections.cpp#L10)) (C++ core guidelines: [R.34](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r34-take-a-shared_ptrwidget-parameter-to-express-that-a-function-is-part-owner))
- Consider making use of [namespaces](https://en.cppreference.com/w/cpp/language/namespace), which were made to avoid `library_name_prefixes`
- Avoid relative include paths
- Consider defining aliases for commonly-used types. `std::shared_ptr<std::map<std::string, std::any>>` is really long.
- Consider using [`ostringstream`](https://en.cppreference.com/w/cpp/io/basic_ostringstream) for concatenating strings ([`graph.cpp`](https://github.com/Azer0s/tinygraph/blob/master/data/graph.cpp#L36))
- Avoid library globals; [this](https://github.com/Azer0s/tinygraph/blob/master/type/type_store.cpp#L10) should probably be contained in an object.

I could open a PR if you'd like, but I don't know if you'd rather look over this yourself.

**Comment by Azer0s** [comment]
Woah, thank you so much! I haven't done a lot with the language in years, so my C++ skills are kinda rusty. Your comments are very much appreciated. ☺️

And sure...if you want to open a PR, feel free to do so ^^

**Comment by Azer0s** [comment]
My idea for the library is to also include a collection of important graph algorithms, persistence features and some utility functions to make working with graphs in C++ as easy as possible. I created the library because I couldn't find a good, general purpose graph library (that allowed both weighted and unweighted graphs, and vertices with properties).

The boost graph library works with an adjacency list which I don't really like too much and other graph libraries either don't allow for weighted graphs or don't allow for vertex properties.

**Comment by svby** [comment]
I've not used the BGL much, but it's quite extensible thanks to its heavy use of templates (which, admittedly, makes it quite complex); I suppose if you want to implement an object graph, it should be possible to make a compatible implementation and take advantage of the BGL's graph algorithms (unless you want to work from scratch, of course.)

I feel like adjacency lists should be alright for most (most) applications, as they are essentially functionally equivalent to object graphs, what use cases are you thinking of?

**Comment by Azer0s** [comment]
No, I don't want to use BGL's algorithms. Especially for partial, lazy loaded or sharded graphs, an object graph is really amazing and the way to go, performance wise. And that is really the way to go, imo (which is also why I want to write the algorithms from scratch - more control, better extensibility).

My vision is a library that supports partial graphs as a first class feature. I have worked with boost subgraphs but they kinda suck tbh and don't _really_ work how I'd imagine them to.

**Comment by Azer0s** [comment]
So as a next step, I'd rewrite all the necessary algorithms and then extend them with partial graph features (something like a `LazyVertex`).

**Comment by svby** [comment]
Seems reasonable, though object ownership and the use of `shared_ptr` means you'll have to think about how to detect/break reference cycles between nodes if you want them to ever be destroyed.

I would suggest using `unique_ptr`s for node ownership and storing raw pointers inside edges, which is fine, since the lifetime of an edge should be shorter than that of the node, and because edges don't conceptually own the nodes they connect to (somewhat related is [R.30](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-smartptrparam): A function that does not manipulate lifetime should take raw pointers or references instead)

**Comment by Azer0s** [comment]
Okay, good to know, thanks! :smile: 
Can I assign this issue to you? Would you be willing to submit a PR? :sweat_smile:

**Comment by svby** [comment]
I don't think I'll have enough time until around the end of May for obvious reasons (blame coronavirus for exam delays 🙃), but if that's fine with you I could probably handle this issue.

I could try to look at smaller parts in the meantime, but I'm not sure how well this will fit in to the (TBD) schedule. If you want to try out some things yourself, perhaps I could do some code review or discuss ideas (twitter dms? dunno)

**Comment by Azer0s** [comment]
Understandable. Would you mind reviewing the changes tho? I would very much appreciate that ^^

**Comment by Azer0s** [comment]
@stuhlmeier PR is ready https://github.com/Azer0s/tinygraph/pull/2 ^^
Hope I didn't miss anything. Thanks in advance! Learned a lot through your &pointers :smile:

**Comment by svby** [comment]
Looks good so far, I've added some comments.

If you don't mind, I'll probably submit some changes for less-critical stuff when I have more time.
